### PR TITLE
Clean country

### PR DESCRIPTION
**Pull request by MattiaSilvestri**
Changes:
- add searchable menu if user replies "n" to the disclaimer question;
- add searchable menu when calling program with flag --show-list and run program after user selected the country.
The searchable menu has search on typing feature, so no forward slash needed.

### CODE REVIEW

**Comment by MattiaSilvestri** [comment]
I should have solved the issue with the menu for Windows, you should update your python packages with the requirements.txt to try it because I'm using a different package. 
In general the added featuers are:
- searchable terminal menu with filter on type and fuzzy-finder features (now also for Windows),
- confirmation message after country have been selected,
- cute frame around the menu.

**Comment by FrnRmn** [comment]
Thanks, now it works in windows too.
Amazing.
The only problem I found is that the program interrupts if you first say no to geolocalization, then select any country, and then you say no to the prompt "Confirm?". In this case I got "Sorry, your country is not present in the Electricity Map database, it is therefore not possible to retrieve CO2 emissions data." as answer, without any chance to insert a new country code.

**Comment by MattiaSilvestri** [comment]
> Thanks, now it works in windows too. Amazing. The only problem I found is that the program interrupts if you first say no to geolocalization, then select any country, and then you say no to the prompt "Confirm?". In this case I got "Sorry, your country is not present in the Electricity Map database, it is therefore not possible to retrieve CO2 emissions data." as answer, without any chance to insert a new country code.

Ah right I didn't think about it, I actually was not sure whether or not to keep the confirmation question. I'll see if it's possible to quickly fix it.

**Comment by FrnRmn** [comment]
Not a big deal btw, we can also merge and fix this later for me

**Comment by MattiaSilvestri** [comment]
Solved, it just needed a while loop :)

**Review by FrnRmn — APPROVED** [review]
lgtm

**Review by giulianogiari — APPROVED** [review]
lgtm

**Pull request merged**
